// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TERMSTRUCTUREPOINTS_QUANTRA_H_
#define FLATBUFFERS_GENERATED_TERMSTRUCTUREPOINTS_QUANTRA_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"
#include "enums_generated.h"
#include "term_structure_generated.h"

#endif  // FLATBUFFERS_GENERATED_TERMSTRUCTUREPOINTS_QUANTRA_H_
