// automatically generated by the FlatBuffers compiler, do not modify

export enum DateGenerationRule{
  Backward = 0,
  CDS = 1,
  Forward = 2,
  OldCDS = 3,
  ThirdWednesday = 4,
  Twentieth = 5,
  TwentiethIMM = 6,
  Zero = 7
}

