// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_QUANTRASERVER_QUANTRA_H_
#define FLATBUFFERS_GENERATED_QUANTRASERVER_QUANTRA_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"
#include "enums_generated.h"
#include "fixed_rate_bond_generated.h"
#include "floating_rate_bond_generated.h"
#include "index_generated.h"
#include "price_fixed_rate_bond_request_generated.h"
#include "responses_generated.h"
#include "schedule_generated.h"
#include "term_structure_generated.h"

#endif  // FLATBUFFERS_GENERATED_QUANTRASERVER_QUANTRA_H_
