// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { BusinessDayConvention } from '../quantra/enums/business-day-convention';
import { Calendar } from '../quantra/enums/calendar';
import { DayCounter } from '../quantra/enums/day-counter';


export class FRAHelper {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):FRAHelper {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFRAHelper(bb:flatbuffers.ByteBuffer, obj?:FRAHelper):FRAHelper {
  return (obj || new FRAHelper()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFRAHelper(bb:flatbuffers.ByteBuffer, obj?:FRAHelper):FRAHelper {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FRAHelper()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

rate():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

monthsToStart():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

monthsToEnd():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

fixingDays():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

calendar():Calendar {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : Calendar.Argentina;
}

businessDayConvention():BusinessDayConvention {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : BusinessDayConvention.Following;
}

dayCounter():DayCounter {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : DayCounter.Actual360;
}

static startFRAHelper(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addRate(builder:flatbuffers.Builder, rate:number) {
  builder.addFieldFloat32(0, rate, 0.0);
}

static addMonthsToStart(builder:flatbuffers.Builder, monthsToStart:number) {
  builder.addFieldInt32(1, monthsToStart, 0);
}

static addMonthsToEnd(builder:flatbuffers.Builder, monthsToEnd:number) {
  builder.addFieldInt32(2, monthsToEnd, 0);
}

static addFixingDays(builder:flatbuffers.Builder, fixingDays:number) {
  builder.addFieldInt32(3, fixingDays, 0);
}

static addCalendar(builder:flatbuffers.Builder, calendar:Calendar) {
  builder.addFieldInt8(4, calendar, Calendar.Argentina);
}

static addBusinessDayConvention(builder:flatbuffers.Builder, businessDayConvention:BusinessDayConvention) {
  builder.addFieldInt8(5, businessDayConvention, BusinessDayConvention.Following);
}

static addDayCounter(builder:flatbuffers.Builder, dayCounter:DayCounter) {
  builder.addFieldInt8(6, dayCounter, DayCounter.Actual360);
}

static endFRAHelper(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFRAHelper(builder:flatbuffers.Builder, rate:number, monthsToStart:number, monthsToEnd:number, fixingDays:number, calendar:Calendar, businessDayConvention:BusinessDayConvention, dayCounter:DayCounter):flatbuffers.Offset {
  FRAHelper.startFRAHelper(builder);
  FRAHelper.addRate(builder, rate);
  FRAHelper.addMonthsToStart(builder, monthsToStart);
  FRAHelper.addMonthsToEnd(builder, monthsToEnd);
  FRAHelper.addFixingDays(builder, fixingDays);
  FRAHelper.addCalendar(builder, calendar);
  FRAHelper.addBusinessDayConvention(builder, businessDayConvention);
  FRAHelper.addDayCounter(builder, dayCounter);
  return FRAHelper.endFRAHelper(builder);
}
}
