// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Index } from '../quantra/index';
import { Schedule } from '../quantra/schedule';
import { BusinessDayConvention } from '../quantra/enums/business-day-convention';
import { DayCounter } from '../quantra/enums/day-counter';


export class FloatingRateBond {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):FloatingRateBond {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFloatingRateBond(bb:flatbuffers.ByteBuffer, obj?:FloatingRateBond):FloatingRateBond {
  return (obj || new FloatingRateBond()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFloatingRateBond(bb:flatbuffers.ByteBuffer, obj?:FloatingRateBond):FloatingRateBond {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FloatingRateBond()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

settlementDays():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

faceAmount():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

schedule(obj?:Schedule):Schedule|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Schedule()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

index(obj?:Index):Index|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Index()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

accrualDayCounter():DayCounter {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : DayCounter.Actual360;
}

paymentConvention():BusinessDayConvention {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : BusinessDayConvention.Following;
}

fixingDays():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

spread():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

inArrears():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

redemption():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

issueDate():string|null
issueDate(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
issueDate(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startFloatingRateBond(builder:flatbuffers.Builder) {
  builder.startObject(11);
}

static addSettlementDays(builder:flatbuffers.Builder, settlementDays:number) {
  builder.addFieldInt32(0, settlementDays, 0);
}

static addFaceAmount(builder:flatbuffers.Builder, faceAmount:number) {
  builder.addFieldFloat64(1, faceAmount, 0.0);
}

static addSchedule(builder:flatbuffers.Builder, scheduleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, scheduleOffset, 0);
}

static addIndex(builder:flatbuffers.Builder, indexOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, indexOffset, 0);
}

static addAccrualDayCounter(builder:flatbuffers.Builder, accrualDayCounter:DayCounter) {
  builder.addFieldInt8(4, accrualDayCounter, DayCounter.Actual360);
}

static addPaymentConvention(builder:flatbuffers.Builder, paymentConvention:BusinessDayConvention) {
  builder.addFieldInt8(5, paymentConvention, BusinessDayConvention.Following);
}

static addFixingDays(builder:flatbuffers.Builder, fixingDays:number) {
  builder.addFieldInt32(6, fixingDays, 0);
}

static addSpread(builder:flatbuffers.Builder, spread:number) {
  builder.addFieldFloat64(7, spread, 0.0);
}

static addInArrears(builder:flatbuffers.Builder, inArrears:boolean) {
  builder.addFieldInt8(8, +inArrears, +false);
}

static addRedemption(builder:flatbuffers.Builder, redemption:number) {
  builder.addFieldFloat64(9, redemption, 0.0);
}

static addIssueDate(builder:flatbuffers.Builder, issueDateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, issueDateOffset, 0);
}

static endFloatingRateBond(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


serialize():Uint8Array {
  return this.bb!.bytes();
}

static deserialize(buffer: Uint8Array):FloatingRateBond {
  return FloatingRateBond.getRootAsFloatingRateBond(new flatbuffers.ByteBuffer(buffer))
}
}
