// automatically generated by the FlatBuffers compiler, do not modify

export enum BusinessDayConvention{
  Following = 0,
  HalfMonthModifiedFollowing = 1,
  ModifiedFollowing = 2,
  ModifiedPreceding = 3,
  Nearest = 4,
  Preceding = 5,
  Unadjusted = 6
}

